### ISSUE TITLE
Auto convert Italics

### ISSUE THREAD

**Issue by ShunKaiser** [DearVikki/obsidian-cloze-plugin#10]
Hi, 

I noticed that the auto convert feature has options for auto convert bold, highlight, and underline. I would like to ask if the team can add another option for italics. Since my friends and I use italics most of the time to highlight the keywords in the lesson, adding it would be a tremendous help for us. 

The Cloze plugin has changed my way of using Obsidian for learning and recalling information. Thank you for making it!

**Comment by DearVikki** [comment]
Hi Kaiser, I'm so glad to hear that the plugin has been helpful for you. Absolutely, adding an option for italics is not a problem at all! I'll let you know as soon as it's available in the next version. :D

**Comment by ShunKaiser** [comment]
> Hi Kaiser, I'm so glad to hear that the plugin has been helpful for you. Absolutely, adding an option for italics is not a problem at all! I'll let you know as soon as it's available in the next version. :D

Thank you very much! I'm looking forward to seeing it.

**Comment by DearVikki** [comment]
@ShunKaiser Ta-Da! You can find the latest release (version 0.1.10) and the option for italics will be there. Give it a try, and I hope it works all well for you. 😃

**Comment by ShunKaiser** [comment]
It works beautifully. Thank you soo much! Have a nice day @DearVikki.

**Comment by iwchang** [comment]
Hello Vikki, may I ask if it's possible to add an option, such as not letting abc automatically become italic when I type an underlined sentence like "\_abc\_", and keeping it in the underlined state? Although this is the basic markdown syntax of obsidian, I basically don't need to use this syntax. I would prefer to use "*" instead of "_". However, I'm not good at this  and I don't know how to modify it, so I'm taking the liberty of making this request to you. I hope you can help me, thank you very much for your contribution.

**Comment by DearVikki** [comment]
Hi @iwchang,

Sadly, the plugin can't do anything about it since Obsidian automatically transforms underlined sentences into italics. However, there are two choices for you to address this problem by modifying your markdown syntax a little bit:

Way 1: You can put a backslash (\) in front of each underscore (_).

Way 2: Enclose the underlined sentence within double backticks (``).

Good luck with your work!

**Comment by iwchang** [comment]
Dear Vikki,

Thank you for your reply. As I rarely take notes on code, the solution you mentioned, Option 2, is a solution that I had not thought of before. I just tried option two, which provided me with a complete replacement method. Thank you very much for your reply and useful suggestions!

Best Regard,
iwchang
