### ISSUE TITLE
Toggle all clozes icon or command not working

### ISSUE THREAD

**Issue by tzugme** [DearVikki/obsidian-cloze-plugin#18]
Also, some clozes stay "revealed" and need to be clicked to work again

**Comment by DearVikki** [comment]
Hi @tzugme! I'd really appreciate it if you could give me some more info to help me understand things better:
1. Cloze type: Are the cloze types customizable, automatically transformed, or both?
2. I'm curious if clicking the "toggle all clozes" icon only toggles a specific number of clozes (like the ones in the visible area) in certain notes, or if it doesn't work at all.
3. If it's convenient for you, could you please test it again in the Obsidian sandbox? That way, we can see if there are any other plugins causing this issue. 

Thanks again for all your support! :D

**Comment by VerAn1015** [comment]
@DearVikki Tested this one in Obsidian sandbox. Succeeding tabs opened after the 1st tab is not affected when clicking "Toggle all clozes" icon or through the command palette.

To reproduce, 
1. Open Obsidian sandbox and install the plugin. 
2. Turn on auto convert bolded text (haven't tried other types)
3. Open only 1 tab with a cloze. Clicking "Toggle all clozes" icon or through the command palette will still work here.
4. Open another tab with a cloze. Clicking "Toggle all clozes" icon or through the command palette will no longer work here and for any succeeding tabs opened. 
5. However, if you go back to the 1st tab opened, it will work there.

**Comment by DearVikki** [comment]
Hi @VerAn1015 thank you so much for the valuable feedback!! I've already identified the problem and will fix it asap in the next version. :D

**Comment by VerAn1015** [comment]
Thanks @DearVikki! Toggle all clozes icon or command now works with multiple tabs opened! Unfortunately, I found another bug still related to this issue while testing 💀.

# Toggle all clozes icon or command does not work in embedded reference blocks when switching from live preview mode to reading view. 

Attached below are steps with images to reproduce the said issue,
1. Open Sandbox Vault, install and enable plugin. Turn on auto convert bolded text. 
![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/6b1ebb3d-8057-4325-a13b-bb297d6ef5e6)

2. Create a note containing a block with clozes.
![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/826802b4-f576-4801-9b4e-48df1a502bcf)

3. Create another note and embed the reference block containing the cloze 
![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/f17e19bd-0d39-4ad3-a5d3-2517ee1a2ba8)

4. Make sure you are in live preview mode and not in source mode.
![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/39a41706-c142-4f68-b144-03c005e9c853)

5. Switch to reading view and click the toggle all clozes icon or command. You can see that the all clozes, both part of the embedded reference block and not part, are unaffected by the toggle all clozes icon or command. 
![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/b6afbec0-265e-41ab-a926-103ee72ca4f7)![image](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/e3c14483-455a-49e8-ba66-0a547a442b93)

Note: The issue is fixed if you switch from source mode to reading view (The toggle all clozes icon or command works.). It is only specific to when you switch from live preview mode to reading view. 

Apologies for finding another issue immediately ☠

**Comment by DearVikki** [comment]
Haha @VerAn1015, wow, you are so efficient! 

However, I followed your steps but didnt reproduce the same result. Could you please check if I missed any points?

![cloze-test](https://github.com/DearVikki/obsidian-cloze-plugin/assets/18145936/a2996bba-dda6-4a67-bfb9-aae016595267)

My Environment: Mac with obsidian v1.5.3

P.S. Never feel bad about your bug-hunting skills, I need them so much 😆

**Comment by VerAn1015** [comment]
Hello @DearVikki. It seems like you clicked the toggle all icon when you were in live preview mode. Try clicking it when you are in reading view 😁. 

Windows 10
Obsidian Version: 1.5.3
Installer Version: 1.5.3

![Obsidian_dXfkGDpiFk](https://github.com/DearVikki/obsidian-cloze-plugin/assets/148541981/aa187ddd-7a16-4804-b2e6-22158e183b69)

**Comment by DearVikki** [comment]
Hi @VerAn1015 got that! Now you may try the latest version(0.0.14), and I hope it will pass all the tests. 😆

**Comment by VerAn1015** [comment]
All tests have passed so far @DearVikki 😂. Toggle all clozes icon or command is back to working in both multiple tabs opened and in the presence of an embedded reference block 🎉
Thank you for your work!

**Comment by DearVikki** [comment]
Yay glad to hear that, thank you my quality assurance specialist!😄
