### ISSUE TITLE
Cloze cannot be invisible in mobile devices

### ISSUE THREAD

**Issue by ELainelyp** [DearVikki/obsidian-cloze-plugin#4]
Hi, thanks for creating such a great plugin. It is very helpful for doing review. Except when it displays in mobile devices all cloze are visible only. Could you help to upgrade it ASAP? Cheers.

**Comment by DearVikki** [comment]
Hi @ELainelyp , I'm sorry to hear that. 

Perhaps it's a silly question, but just in case, could you make sure that you're in reading mode? Which means you will see this tiny "pencil" icon instead of the "book" icon at the bottom of the page, and you cannot edit text under this mode.

<img width="386" alt="image" src="https://github.com/DearVikki/obsidian-cloze-plugin/assets/18145936/a9621f17-c771-4d79-8e4f-75ba6b47be3a">

If that didnt help (which I dont really wish for 😞 ), please let me know which mobile device you are using, as well as the version of Obsidian.

Thanks again for your support and patience. 😃
